### ISSUE TITLE
Feature: Find a friend

### ISSUE THREAD

**Issue by jpkrieg** [jpkrieg/socialbet#39]

**Comment by chappstick9** [comment]
Acceptance Criteria:
--Given I’m a logged-in user, when I start to type in a friend’s name or handle into the search bar, then some friends’ names should appear below for me to click
--Given I’m a logged-in user searching for a friend, when I click on one of the names beneath the search bar, I should be taken to that friend’s profile

**Comment by jpkrieg** [comment]
Fibonacci Rating: 5
