### ISSUE TITLE
Feature: Initiate a direct bet

### ISSUE THREAD

**Issue by jpkrieg** [jpkrieg/socialbet#42]

**Comment by chappstick9** [comment]
Acceptance Criteria:
--Given that I am a logged-in user who has navigated to a friend’s profile, when I click “Bet Me”, then I should be directed to the Bet Builder to create a direct bet with this friend
--Given that I am in the Bet Builder, I should be able to select a specific team to bet on in a specific upcoming game

**Comment by jpkrieg** [comment]
Fibonacci Rating: 5
