### ISSUE TITLE
Feature: Initiate an open bet

### ISSUE THREAD

**Issue by jpkrieg** [jpkrieg/socialbet#43]

**Comment by chappstick9** [comment]
Acceptance Criteria:
--Given that I am a logged-in user, when I open the Bet Builder, I should have the option to create an “Open Bet” where I assign 0 friends
--Given that I have created an Open Bet, when I navigate to “Open Bets” I should see my bet displayed in the feed

**Comment by jpkrieg** [comment]
Fibonacci Rating: 5
