### ISSUE TITLE
Feature: Accept a direct bet

### ISSUE THREAD

**Issue by jpkrieg** [jpkrieg/socialbet#46]

**Comment by chappstick9** [comment]
Acceptance Criteria:
--Given that I am a logged-in user, when I click “Requests” I should see a list of all requests that I have sent to friends or they have sent to me
--Given that I am looking at this list of requests, when I click “Accept”, I should be locked into that bet, and should receive confirmation of that

**Comment by jpkrieg** [comment]
Fibonacci Rating: 5
