### ISSUE TITLE
Feature: Decline a direct bet

### ISSUE THREAD

**Issue by jpkrieg** [jpkrieg/socialbet#47]

**Comment by chappstick9** [comment]
Acceptance Criteria: 
--Given that I am a logged-in user viewing my list of requests, when I click “Decline” on a specific bet, that request should disappear from the list and I should not be locked into that bet

**Comment by jpkrieg** [comment]
Fibonacci Rating: 5

**Comment by rshelly8** [comment]
we use a cancel_bet endpoint, implementation found in backend/api/betting.py
