### ISSUE TITLE
Feature: Accept an open bet

### ISSUE THREAD

**Issue by jpkrieg** [jpkrieg/socialbet#49]

**Comment by chappstick9** [comment]
Acceptance Criteria: 
--Given that I am a logged-in user who is viewing the list of Open Bets initialized by my friends, when I click the handshake icon on a specific bet, I should be locked into that bet. Additionally, this bet should be removed from the Open Bets list and moved to my Live Bets list.

**Comment by jpkrieg** [comment]
Fibonacci Rating: 5
